### ISSUE TITLE
Failure to run `./scripts/eval_bts.sh`

### ISSUE THREAD

**Issue by AbolfazlMhamdi** [kaen2891/bts#2]
Hello I went through the steps I mentioned with Ubuntu 20.04 and the rest of the requirements, and in the end, when I try to execute the command `./scripts/eval_bts.sh` , it gives this error:

"python: can't open file 'prac_lime.py': [Errno 2] No such file or directory"
![Screenshot 2024-10-18 180628](https://github.com/user-attachments/assets/5ee3baac-6c78-404a-9f70-2bdcc38569e3)

I have attached a shot of the terminal. I also had a question about the  `--pretrained_ckpt` section. what's this ?!

**Comment by kaen2891** [comment]
Hey, sorry for late reply.

The error you reported is my mistake. I will modify it ASAP. 

By the way, the reason why ```41998 Killed``` implies that your CPU capacity seems not enough to preprocessing ICBHI dataset.

**Comment by kaen2891** [comment]
Hey @AbolfazlMhamdi ,

I've refactored the code—apologies, the previous evaluation script wasn’t the correct file.

I’ve uploaded the updated evaluation [here](https://github.com/kaen2891/bts/blob/main/scripts/eval_bts.sh). 

Note that this evaluation script requires pretrained checkpoints.

Please give it a run and let me know if your concerns are addressed!

**Comment by AbolfazlMhamdi** [comment]
> Hey, sorry for late reply.
> 
> The error you reported is my mistake. I will modify it ASAP.
> 
> By the way, the reason why `41998 Killed` implies that your CPU capacity seems not enough to preprocessing ICBHI dataset.

Hey @kaen2891,
Thanks for your reply. But I'm using an Asus laptop with pretty good specs. My processor is a 13th generation Intel (core i7 - 13650HX) and my graphics card is an RTX4060. Don't you think the problem might be with the code?

![Screenshot 2024-12-19 145529](https://github.com/user-attachments/assets/251451d2-dc7c-41ff-9e3b-508164d6fb62)

**Comment by kaen2891** [comment]
Hi @AbolfazlMhamdi,

I have reviewed our code, and there are no errors. The `388199 Killed` message in your figure appears to be related to `CPU` or `RAM` issues. It seems to have occurred during the data preprocessing stage. Please check your laptop's capacity using tools like `htop` or `top`.
