### ISSUE TITLE
Setting Seed

### ISSUE THREAD

**Issue by wa976** [kaen2891/bts#3]
Hello thank you for sharing this code!
I tried running this code on my server, but I encountered an issue: 
even though I set a fixed seed, the results change each time I run the script.
Could you let me know if this is expected behavior for the code, or if I might be incorrectly setting the seed? 
Thank you!

**Comment by kaen2891** [comment]
Hi,

We have also observed these issues are caused by the Swin Transformer module in CLAP.

Even though the random seed is fixed, results can differ due to the non-determinism issue of PyTorch \emph{upsample-bicubic2d-backward} in the implementation of the Swin Transformer module in CLAP.

**Comment by wa976** [comment]
Thank you for reply!
i got it
